In [2]:
from sklearn.feature_extraction.text import CountVectorizer #importer une classe CountVectorizer et une package text
texte = ["La vie est douce","La vie est tranquille,est ou belle,est douce","hello Rihab"] #une liste (vecteur) de deux texts
vect = CountVectorizer() #instantiation 
T=vect.fit_transform(texte) #count how many times each word existed in the given data set
dictionnaire_des_mots=vect.vocabulary_ #attribut de la classe vect ( CountVectorizer)
print("dictionnaire_des_mots:",dictionnaire_des_mots)
liste_des_mots=list(dictionnaire_des_mots.keys()) #retourner les motes sans valeurs sous forme d'une liste
print("liste_des_mots:",liste_des_mots)
Matrice_sparse_correspondante=T.toarray() 
print("Matrice_sparse_correspondante:\n",Matrice_sparse_correspondante)
print(T)

dictionnaire_des_mots: {'la': 4, 'vie': 8, 'est': 2, 'douce': 1, 'tranquille': 7, 'ou': 5, 'belle': 0, 'hello': 3, 'rihab': 6}
liste_des_mots: ['la', 'vie', 'est', 'douce', 'tranquille', 'ou', 'belle', 'hello', 'rihab']
Matrice_sparse_correspondante:
 [[0 1 1 0 1 0 0 0 1]
 [1 1 3 0 1 1 0 1 1]
 [0 0 0 1 0 0 1 0 0]]
  (0, 4)	1
  (0, 8)	1
  (0, 2)	1
  (0, 1)	1
  (1, 4)	1
  (1, 8)	1
  (1, 2)	3
  (1, 1)	1
  (1, 7)	1
  (1, 5)	1
  (1, 0)	1
  (2, 3)	1
  (2, 6)	1


In [3]:
import string
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\T460s\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [4]:
def netoyage(corpus_ensemble_documents):
    for i in range(len(corpus_ensemble_documents)):
        corpus_ensemble_documents[i]=corpus_ensemble_documents[i].lower()
    for i in range(len(corpus_ensemble_documents)):
        for c in string.punctuation:
            x=corpus_ensemble_documents[i].replace(c,'')
            corpus_ensemble_documents[i]=x
    stopwords_anglais = stopwords.words('french') #ou french
    for i in range(len(corpus_ensemble_documents)):
        L = corpus_ensemble_documents[i].split()
        for mot in L:
            if mot in stopwords_anglais:
                while mot in L:
                    L.remove(mot)
        corpus_ensemble_documents[i] = " ".join(L)
    return(corpus_ensemble_documents) 
print(netoyage(["La vie en rose?","  dans la Foret il y a un Lion ...",".. la vie est tres douce!"]))

['vie rose', 'la foret y a lion', 'vie tres douce']


In [38]:
#exo spams

import numpy 
def TF(terme,corpus,numero_document):
    x=corpus[numero_document].count(terme)
    y=len(corpus[numero_document].split())
    return x/y
def IDF(terme,corpus,numero_document):
    D=len(corpus)
    d_t=0
    for document in corpus:
        if terme in document:
            d_t+=1
    TF_VAL=TF(terme,corpus,numero_document)
    return TF_VAL*log(1+(D/d_t))
def cles_correspondante_a_valeur(valeur,dictionnaire):
    for cle in dictionnaire.keys():
        if dictionnaire[cle]==valeur:
            return cle
def matrice_sparse(dictionnaire,corpus_ensemble_documents):
    M=numpy.zeros((len(corpus_ensemble_documents),len(dictionnaire.values())))
    for i in range(len(corpus_ensemble_documents)):
        for j in dictionnaire.values():
            x=cles_correspondante_a_valeur(j,dictionnaire)
            M[i,j]=IDF(x,corpus_ensemble_documents,i)
    return M
def affiche(M):
    (n,p)=M.shape
    for i in range(n):
        for j in range(p):
            M[i,j]=round(M[i,j],2)
    print(M)  
    


In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer #importer une classe CountVectorizer et une package text
import nltk
texte = ["La vie est douce","La vie est tranquille,est ou belle,est douce","le corona-virus est méchant"] #une liste (vecteur) de deux texts
texte=netoyage(texte)
vect=TfidfVectorizer()
T=vect.fit_transform(texte) #count how many times each word existed in the given data set
dictionnaire_des_mots=vect.vocabulary_ #attribut de la classe vect ( CountVectorizer)
print("dictionnaire_des_mots:",dictionnaire_des_mots)
liste_des_mots=list(dictionnaire_des_mots.keys()) #retourner les motes sans valeurs sous forme d'une liste
print("liste_des_mots:",liste_des_mots)
Matrice_sparse_correspondante=T.toarray() 
print("Matrice_sparse_methode_predefinie:\n")
affiche(Matrice_sparse_correspondante)
print("Matrice_sparse obtenue par notre methode :\n")
affiche(matrice_sparse(dictionnaire_des_mots,texte))


#print(T)

dictionnaire_des_mots: {'vie': 5, 'douce': 2, 'tranquilleest': 4, 'belleest': 0, 'coronavirus': 1, 'méchant': 3}
liste_des_mots: ['vie', 'douce', 'tranquilleest', 'belleest', 'coronavirus', 'méchant']
Matrice_sparse_methode_predefinie:

[[0.   0.   0.71 0.   0.   0.71]
 [0.56 0.   0.43 0.   0.56 0.43]
 [0.   0.71 0.   0.71 0.   0.  ]]
Matrice_sparse obtenue par notre methode :

[[0.   0.   0.46 0.   0.   0.46]
 [0.35 0.   0.23 0.   0.35 0.23]
 [0.   0.69 0.   0.69 0.   0.  ]]


In [24]:
import numpy as np
import pandas
from sklearn.model_selection import train_test_split
spams = pandas.read_table("C:\SMSSpamCollection.txt",sep="\t",header=0)
spamsTrain,spamsTest = train_test_split(spams,train_size=0.7,random_state=1)
from sklearn.feature_extraction.text import CountVectorizer
parseur = CountVectorizer()
XTrain = parseur.fit_transform(spamsTrain['message'])
mdtTrain = XTrain.toarray()
from sklearn.linear_model import LogisticRegression
modelFirst = LogisticRegression()
#modelFisrt.fit(spamsTrain['message'],spamsTrain['classe'])
modelFirst.fit(mdtTrain,spamsTrain['classe'])
score1=modelFirst.score(mdtTrain,spamsTrain['classe'])
print("score sur data train:"+str(score1))
mdtTest=parseur.transform(spamsTest['message'])
#predTest=modelFirst.predict(mdtTest)
score2=modelFirst.score(mdtTest,spamsTest['classe'])
print("score sur data test:"+str(score2))

score sur data train:0.9976923076923077
score sur data test:0.9814593301435407


In [40]:
import numpy as np
import pandas
spams = pandas.read_table("C:\Users\T460s\Documents\SMSSpamCollection.txt" ,sep="\t",header=0)
spamsTrain,spamsTest = train_test_split(spams,train_size=0.7,random_state=1)
from sklearn.feature_extraction.text import CountVectorizer
parseur = CountVectorizer(binary=True)
Xtrain = parseur.fit_transform(spamsTrain['message'])
mdtTrain = XTrain.toarray()
from sklearn.linear_model import LogisticRegression
modelFirst = LogisticRegression()
#modelFisrt.fit(spamsTrain['message'],spamsTrain['classe'])
modelFisrt.fit(mdtTrain,spamsTrain['classe'])
score1=modelFirst.score(mdtTrain,spamsTrain['classe'])
print("score sur data train:"+str(score1))
mdtTest=parseur.transform(spamsTest['message'])
#predTest=modelFirst.predict(mdtTest)
score2=modelFisrt.score(mdtTest,spamTest['classe'])
print("score sur data test:"+str(score2))

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (Temp/ipykernel_4384/1471105588.py, line 3)

In [29]:
from sklearn import metrics
parseurBis=CountVectorizer(stop_words='english')
XTrainBis=parseurBis.fit_transform(spamsTrain['message'])
mdtTrainBis=XTrainBis.toarray()
modelBis=LogisticRegression()
modelBis.fit(mdtTrainBis,spamsTrain['classe'])
mdtTestBis=parseurBis.transform(spamsTest['message'])
score3=modelBis.score(mdtTrainBis,spamsTrain['classe'])
print("score sur data train:"+str(score3))
score4=modelBis.score(mdtTestBis,spamsTest['classe'])
print("score sur data test:"+str(score4))


score sur data train:0.9953846153846154
score sur data test:0.9760765550239234


In [30]:
from sklearn import metrics
parseur3=TfidfVectorizer()
XTrain3=parseur3.fit_transform(spamsTrain['message'])
mdtTrain3=XTrain3.toarray()
model3=LogisticRegression()
model3.fit(mdtTrain3,spamsTrain['classe'])
mdtTest3=parseur3.transform(spamsTest['message'])
score5=model3.score(mdtTrain3,spamsTrain['classe'])
print("score sur data train:"+str(score5))
score6=model3.score(mdtTest3,spamsTest['classe'])
print("score sur data test:"+str(score6))


score sur data train:0.9743589743589743
score sur data test:0.9712918660287081
