In [1]:
from numpy import *
X= [[0,0,1],[0,1,0],[1,0,0],[0,1,1],[0,1,0],[0,1,1]]
from sklearn.feature_selection import VarianceThreshold
Filtre = VarianceThreshold(threshold=0.2)
Donnes_filtrees = Filtre.fit_transform(X)
print(array(X))
print(Donnes_filtrees)
print(var(X,axis=0))

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 1 1]]
[[0 1]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]]
[0.13888889 0.22222222 0.25      ]


In [13]:
from sklearn.feature_selection import VarianceThreshold
from sklearn.datasets import load_iris
iris = load_iris(); X=iris.data ; Y=iris.target
import matplotlib.pyplot as plt
#plt.plot(); plt.legend(iris.feature_names); plt.show()

print(X.var(axis=0))
Filtre = VarianceThreshold(threshold=0.18872)
Donnes_filtrees=Filtre.fit_transform(X)
#print(Donnes_filtrees)
Filtre.get_support()

[0.68112222 0.18871289 3.09550267 0.57713289]


array([ True, False,  True,  True])

In [15]:
from sklearn.feature_selection import SelectFromModel 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

#creating the models
model1=KNeighborsClassifier()
model2=DecisionTreeClassifier()
model3=LogisticRegression(C=10e+10)

#creating the selectors
selector=SelectFromModel(model2, threshold='mean')
selector.fit_transform(X,Y); print(selector.get_support())

selector=SelectFromModel(model3, threshold='mean')
selector.fit_transform(X,Y); print(selector.get_support())

[False False False  True]
[False  True  True False]


In [16]:
from sklearn.feature_selection import VarianceThreshold

def trouver_donnees_importantes(X_train,TR):
    Filtre=VarianceThreshold(threshold=TR)
    Donnees_filtrees=Filtre.fit_transform(x_train)
    FS=list(Filtre.get_support())
    X=[]
    for i in range(0,len(FS)):
        if FS[i]==True:
            X+=i
    return tuple(X)        

In [2]:
chi2_selector = SelectKBest(chi2, k=2)
X_kbest = chi2_selector.fit_transform(X, y)
print(X_kbest)

NameError: name 'SelectKBest' is not defined